package shell

import (
	"os"
	"path/filepath"
	"strings"
)

func WriteAliases(sh string, lines []string) (string, error) {
	home, _ := os.UserHomeDir()
	dir := filepath.Join(home, ".config", "aliasgen")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	ext := "sh"
	if sh == "fish" {
		ext = "fish"
	}
	target := filepath.Join(dir, "aliases."+ext)
	header := "# generated by aliasgen — do not edit manually\n\n"
	content := header + strings.Join(lines, "\n") + "\n"
	return target, os.WriteFile(target, []byte(content), 0o644)
}

// SourceHint devolve instruções para fazer source do arquivo de aliases
func SourceHint(sh string) string {
	switch sh {
	case "bash":
		return `Adicione ao final do ~/.bashrc:
[ -f "$HOME/.config/aliasgen/aliases.sh" ] && source "$HOME/.config/aliasgen/aliases.sh"`
	case "zsh":
		return `Adicione ao final do ~/.zshrc:
[ -f "$HOME/.config/aliasgen/aliases.sh" ] && source "$HOME/.config/aliasgen/aliases.sh"`
	case "fish":
		return `Adicione ao ~/.config/fish/config.fish:
test -f ~/.config/aliasgen/aliases.fish; and source ~/.config/aliasgen/aliases.fish`
	default:
		return "Shell desconhecido — adicione manualmente o source do arquivo em ~/.config/aliasgen/aliases.{sh|fish} no seu arquivo RC."
	}
}
